package agh.project.oot;

public enum MessageType {
    UPLOAD_IMAGES,
    GET_ALL_SMALL_THUMBNAILS,
    GET_ALL_MEDIUM_THUMBNAILS,
    GET_ALL_BIG_THUMBNAILS,
    GET_IMAGE,
    GET_THUMBNAILS_RESPONSE,
    GET_IMAGE_RESPONSE,
    INFO_RESPONSE,
    PING,
    PONG
}