enum MessageTypes {
    UPLOAD_IMAGES = "UPLOAD_IMAGES",
    UPLOAD_ZIP = "UPLOAD_ZIP",
    GET_IMAGE = "GET_IMAGE",
    GET_THUMBNAILS = "GET_THUMBNAILS",
    DELETE_IMAGE = "DELETE_IMAGE",
    DELETE_FOLDER = "DELETE_FOLDER",
    DELETE_IMAGE_RESPONSE = "DELETE_IMAGE_RESPONSE",
    DELETE_FOLDER_RESPONSE = "DELETE_FOLDER_RESPONSE",
    PLACEHOLDERS_NUMBER_RESPONSE = "PLACEHOLDERS_NUMBER_RESPONSE",
    FOLDERS_RESPONSE = "FOLDERS_RESPONSE",
    INFO_RESPONSE = "INFO_RESPONSE",
    PING = "PING",
    PONG = "PONG",
    GET_NEXT_PAGE = "GET_NEXT_PAGE",
    FETCHING_END_RESPONSE = "FETCHING_END_RESPONSE",
    MOVE_IMAGE = "MOVE_IMAGE",
    MOVE_IMAGE_RESPONSE = "MOVE_IMAGE_RESPONSE"
}

export default MessageTypes;

