enum MessageTypes {
    UPLOAD_IMAGES = "UPLOAD_IMAGES",
    UPLOAD_ZIP = "UPLOAD_ZIP",
    GET_IMAGE = "GET_IMAGE",
    GET_THUMBNAILS = "GET_THUMBNAILS",
    DELETE_IMAGE = "DELETE_IMAGE",
    DELETE_IMAGE_RESPONSE = "DELETE_IMAGE_RESPONSE",
    PLACEHOLDERS_NUMBER_RESPONSE = "PLACEHOLDERS_NUMBER_RESPONSE",
    FOLDERS_RESPONSE = "FOLDERS_RESPONSE",
    INFO_RESPONSE = "INFO_RESPONSE",
    PING = "PING",
    PONG = "PONG",
}

export default MessageTypes;

