enum MessageTypes {
    UPLOAD_IMAGES = "UPLOAD_IMAGES",
    GET_IMAGE = "GET_IMAGE",
    GET_THUMBNAILS = "GET_THUMBNAILS",
    PLACEHOLDERS_NUMBER_RESPONSE = "PLACEHOLDERS_NUMBER_RESPONSE",
    INFO_RESPONSE = "INFO_RESPONSE",
    PING = "PING",
    PONG = "PONG",
}

export default MessageTypes;

